[workspace]
members = ["krpc-build"]

[package]
name = "krpc-client"
version = "0.4.1-0.5.1-1.12.5"
authors = ["Kyle Ladd <kyle@ladd.io>"]
edition = "2021"

[features]
docs = ["krpc-build/docs"]

[dependencies]
thiserror = "1.0"
protobuf = { version = "3.2.0", features = ["bytes"] }
bytes = "1.4"

[build-dependencies]
krpc-build = { path = "./krpc-build" }
protobuf-codegen = "3.2.0"