[package]
name = "krpc-build"
version = "0.4.1-0.5.1-1.12.5"
edition = "2021"

[features]
docs = ["dep:xml-rs"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
xml-rs = { version = "0.8.4", optional = true }
convert_case = "0.6.0"
codegen = "0.2.0"
